### ISSUE TITLE
Update Navigation Arrows on Landing Page

### ISSUE THREAD

**Issue by flynnlambrechts** [devsoc-unsw/jobsboard#449]
Currently on the Jobsboard landing page there are arrows that overlap the jobs, move the arrows outside the jobs.

![Image](https://github.com/devsoc-unsw/jobsboard/assets/83333819/4359d97f-fae2-41ce-a090-0868c2af77d4)

**Comment by engooo** [comment]
Resolved with pull request [#466](https://github.com/devsoc-unsw/jobsboard/pull/466)
