### ISSUE TITLE
Inconsistent Button Spacing on Homepage

### ISSUE THREAD

**Issue by flynnlambrechts** [devsoc-unsw/jobsboard#471]
These two sets of buttons are spaced so differently. Make this a bit more nice to look at

![Image](https://github.com/devsoc-unsw/jobsboard/assets/83333819/dfefe28e-5c48-4a5e-8339-c2c342a1c7a2)

**Comment by Ne0phite** [comment]
@flynnlambrechts I'm looking to contribute to open source projects. This seems like a good one to start with. Can you please assign it to me. 

Do you have a preference for either top or bottom set of spacing? Or do you have something else in mind? Thanks

**Comment by Ne0phite** [comment]
Preview of using either top or bottom spacing in both: 
<img width="1250" alt="Screenshot 2024-06-24 at 4 10 31 PM" src="https://github.com/devsoc-unsw/jobsboard/assets/29882680/13f8a3df-0b1b-48a6-8aae-90905943c326">
<img width="1248" alt="Screenshot 2024-06-24 at 4 11 30 PM" src="https://github.com/devsoc-unsw/jobsboard/assets/29882680/2ba4d2d7-1c75-4baa-a142-cb58a5e764bf">

**Comment by flynnlambrechts** [comment]
@Ne0phite  I prefer them close together. I've assigned the issue to you
